interface PaymentDetails {
	id: String!
	creditAccountId: Int!
	amountMoney: Float!
	paymentMethod: PaymentMethod!
	paymentStatus: PaymentStatus!
	paymentDate: Date!
	reference: String!
}

type PaymentDetails {
	id: String!
	creditAccountId: Int!
	amountMoney: Float!
	paymentMethod: PaymentMethod!
	paymentStatus: PaymentStatus!
	paymentDate: Date!
	reference: String!
}

input CreatePaymentDetailsInput {
	creditAccountId: Int!
	amountMoney: Float!
	paymentMethod: PaymentMethod!
	reference: String!
}

type Mutation {
	createPaymentDetails(input: CreateGiftAccountInput): PaymentDetails
}