interface PaymentDetails {
	id: String!
	creditAccountId: Int!
	amountMoney: Float!
	paymentMethod: PaymentMethod!
	paymentStatus: PaymentStatus!
	paymentDate: Date!
	reference: String!
}

type PaymentDetails {
	id: String!
	creditAccountId: Int!
	amountMoney: Float!
	paymentMethod: PaymentMethod!
	paymentStatus: PaymentStatus!
	paymentDate: Date!
	reference: String!
}

input CreatePaymentDetailsInput {
	creditAccountId: Int!
	amountMoney: Float!
	paymentMethod: PaymentMethod!
	reference: String!
}

enum PaymentMethod {
	STRIPE
	MOBILEPAY
	BANK_TRANSFER
	MANUAL
}

enum PaymentStatus {
	PENDING
	COMPLETED
	FAILED
	REFUNDED
}
