version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: asd
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

  mariadb_test:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_DATABASE: asd_test
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_test_data:/var/lib/mysql

volumes:
  mariadb_data:
  mariadb_test_data:
