enum PaymentMethod {
	STRIPE
	MOBILEPAY
	BANK_TRANSFER
	MANUAL
}

enum PaymentStatus {
	PENDING
	COMPLETED
	FAILED
	REFUNDED
}

enum CreditAccountType {
	GIFT_CARD
	PREPAID_CARD
}

enum TransactionType {
	PURCHASE
	USAGE
	NULLIFICATION
	TRANSFER_IN
	TRANSFER_OUT
	REFUND
}