name: Semantic Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const regex = /^(feat|fix|docs|chore|refactor|test|style): .+/;

            if (!regex.test(prTitle)) {
              core.setFailed(`Pull request title "${prTitle}" is invalid. Use format like "feat: add new login form"`);
            }
